# Generated by Django 3.2.11 on 2022-01-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='content-images/')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsetImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='headset-images/')),
            ],
        ),
        migrations.CreateModel(
            name='OutputImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='output-images/')),
            ],
        ),
        migrations.CreateModel(
            name='StyleImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='style_image', max_length=50)),
                ('img', models.ImageField(upload_to='style-images/')),
            ],
        ),
    ]
