# Generated by Django 3.2.11 on 2022-01-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styleTransfer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadsetImagesModel',
        ),
    ]
